"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const portalRoot = path.join(__dirname, "..", "..", "php-update-server");
const read = (name) => fs.readFileSync(path.join(portalRoot, name), "utf8");

test("visitor analytics separates estimated devices, visits and page views", () => {
  const analytics = read("analytics.php");
  assert.match(analytics, /WEB_CONSENT_ACCEPTED/);
  assert.match(analytics, /WEB_CONSENT_REJECTED/);
  assert.match(analytics, /function web_track_visitor\(\)/);
  assert.match(analytics, /bin2hex\(random_bytes\(32\)\)/);
  assert.match(analytics, /hash_hmac\('sha256', "cookieless/);
  assert.match(analytics, /REMOTE_ADDR/);
  assert.match(analytics, /HTTP_USER_AGENT/);
  assert.match(analytics, /flock\(\$handle, LOCK_EX\)/);
  assert.match(analytics, /visitor_retention_days/);
  assert.match(analytics, /function web_visit_stats\(\)/);
  assert.match(analytics, /'visits'/);
  assert.match(analytics, /'pageviews'/);
  assert.match(analytics, /1800/);
});

test("all three consent choices migrate identity and cannot redirect off site", () => {
  const consent = read("consent.php");
  const analytics = read("analytics.php");
  assert.match(consent, /verify_csrf\(\)/);
  assert.match(consent, /WEB_CONSENT_ACCEPTED/);
  assert.match(consent, /WEB_CONSENT_ESSENTIAL/);
  assert.match(consent, /WEB_CONSENT_REJECTED/);
  assert.match(consent, /web_migrate_visitor_hash/);
  assert.match(consent, /web_expire_visitor_cookie/);
  assert.match(consent, /web_safe_return_path/);
  assert.match(analytics, /str_starts_with\(\$value, '\/\/'\)/);
  assert.match(analytics, /httponly.*true/s);
  assert.match(analytics, /samesite.*Lax/s);
});

test("cookie banner and a single visit count are available from every rendered page", () => {
  const partials = read("partials.php");
  const script = read("assets/app.js");
  const protection = read("data/.htaccess");
  assert.match(partials, /web_track_visitor\(\)/);
  assert.match(partials, /web_format_visit_count/);
  assert.doesNotMatch(partials, /web_format_visitor_count\(\$visitStats/);
  assert.match(partials, /data-cookie-banner/);
  assert.match(partials, /action="\/consent\.php"/);
  assert.match(partials, /cookies\.essential/);
  assert.match(partials, /cookies\.reject/);
  assert.match(partials, /cookies\.accept/);
  assert.match(script, /data-cookie-settings/);
  assert.match(protection, /Require all denied/);
});

test("web login and server template use production security controls", () => {
  const config = read("config.php");
  const login = read("login.php");
  const bootstrap = read("bootstrap.php");
  const logout = read("logout.php");
  const nginx = read("nginx-site.conf");
  const coreConfig = fs.readFileSync(path.join(portalRoot, "..", "app", "src", "main", "config", "configStore.js"), "utf8");
  assert.match(config, /CHJ_ADMIN_PASSWORD_HASH/);
  assert.match(config, /CHJ_SECURITY_KEY/);
  assert.doesNotMatch(config, /\$2y\$12\$/);
  assert.doesNotMatch(config, /'admin_password'\s*=>/);
  assert.match(login, /password_verify/);
  assert.match(login, /login_retry_after/);
  assert.match(login, /record_login_failure\(\)/);
  assert.match(login, /login\.banned/);
  assert.match(bootstrap, /session\.use_strict_mode/);
  assert.match(bootstrap, /Content-Security-Policy/);
  assert.match(bootstrap, /WEB_CSP_NONCE/);
  assert.match(bootstrap, /random_bytes\(18\)/);
  assert.match(bootstrap, /default-src 'none'/);
  assert.match(bootstrap, /script-src.*strict-dynamic/);
  assert.match(bootstrap, /script-src-attr 'none'/);
  assert.match(bootstrap, /trusted-types 'none'/);
  assert.match(bootstrap, /require-trusted-types-for 'script'/);
  assert.match(nginx, /Strict-Transport-Security "max-age=86400" always/);
  assert.match(nginx, /Cross-Origin-Opener-Policy "same-origin" always/);
  assert.match(nginx, /X-Content-Type-Options "nosniff" always/);
  assert.match(nginx, /Referrer-Policy "strict-origin-when-cross-origin" always/);
  assert.match(logout, /verify_csrf\(\)/);
  assert.match(logout, /REQUEST_METHOD.*POST/s);
  assert.match(nginx, /client_max_body_size 2100M/);
  assert.match(nginx, /client_max_body_size 64k/);
  assert.match(nginx, /location = \/upload\.php/);
  assert.match(nginx, /auth_request \/_upload-session/);
  assert.match(nginx, /location = \/_upload-session \{.*client_max_body_size 2100M/s);
  assert.match(nginx, /fastcgi_pass_request_body off/);
  assert.doesNotMatch(nginx, /allow 192\.168\.0\.0\/16/);
  assert.match(nginx, /limit_req_zone \$binary_remote_addr zone=chj_admin/);
  assert.match(nginx, /server_name _;/);
  assert.match(nginx, /location \^~ \/data\//);
  assert.match(nginx, /deny all/);
  assert.match(nginx, /listen 443 ssl default_server/);
  assert.match(nginx, /ssl_protocols TLSv1\.2 TLSv1\.3/);
  assert.match(nginx, /ssl_certificate \/etc\/ssl\/certs\/chj-update-server-v2\.crt/);
  assert.match(nginx, /server_name sm\.ch-j\.de/);
  assert.match(nginx, /return 308 https:\/\/www\.sm\.ch-j\.de\$request_uri/);
  assert.match(nginx, /server_name www\.sm\.ch-j\.cz sm\.ch-j\.cz www\.sm\.ch-j\.eu sm\.ch-j\.eu/);
  assert.match(nginx, /return 308 https:\/\/\$host\$request_uri/);
  assert.match(nginx, /server_name www\.sm\.ch-j\.de www\.sm\.ch-j\.cz sm\.ch-j\.cz www\.sm\.ch-j\.eu sm\.ch-j\.eu/);
  assert.doesNotMatch(nginx, /location ~ \^\/api\//);
  assert.match(config, /'base_url'\s*=>\s*'https:\/\/sm\.ch-j\.de'/);
  assert.match(config, /'public_base_url'\s*=>\s*'https:\/\/www\.sm\.ch-j\.de'/);
  assert.match(config, /'allowed_hosts'\s*=>\s*\['www\.sm\.ch-j\.de', 'sm\.ch-j\.de', 'www\.sm\.ch-j\.cz', 'sm\.ch-j\.cz', 'www\.sm\.ch-j\.eu', 'sm\.ch-j\.eu'\]/);
  assert.match(config, /'login_max_attempts'\s*=>\s*3/);
  assert.match(config, /'login_ban_seconds'\s*=>\s*86400/);
  assert.match(config, /'contact_email'\s*=>\s*'support@sm\.ch-j\.de'/);
  assert.match(read("functions.php"), /in_array\(\$requestedHost, \$allowedHosts, true\)/);
  assert.match(bootstrap, /Misdirected Request/);
  assert.match(bootstrap, /\$isApiRequest/);
  assert.match(coreConfig, /https:\/\/www\.sm\.ch-j\.de\//);
  assert.match(coreConfig, /https:\/\/sm\.ch-j\.de\//);
  assert.doesNotMatch(coreConfig, /192\.168\.10\.154/);
  assert.doesNotMatch(coreConfig, /192\.168\.(?:2|10)\.2/);
  const functions = read("functions.php");
  assert.match(functions, /banned_until/);
  assert.match(functions, /LOGIN_ATTEMPTS_LOCK_FILE/);
  assert.match(functions, /tempnam\(dirname\(LOGIN_ATTEMPTS_FILE\)/);
});

test("privacy page documents retention, cookies, community data and data subject rights", () => {
  const privacy = read("privacy.php");
  const partials = read("partials.php");
  const functions = read("functions.php");
  assert.match(partials, /href="\/privacy\.php"/);
  assert.match(partials, /mailto:/);
  assert.match(privacy, /privacy\.controller\.title/);
  assert.match(privacy, /privacy\.data\.community/);
  assert.match(privacy, /privacy\.data\.downloads/);
  assert.match(privacy, /privacy\.rights\.title/);
  assert.match(privacy, /data-cookie-settings/);
  assert.match(functions, /community_actor_retention_seconds/);
  assert.doesNotMatch(functions, /community-message\\n" \. \$remoteAddress \. "\\n" \. \$userAgent/);
});

test("web downloads are counted through a validated release redirect", () => {
  const analytics = read("analytics.php");
  const functions = read("functions.php");
  const download = read("download.php");
  const partials = read("partials.php");
  const releases = read("releases.php");
  assert.match(analytics, /WEB_DOWNLOAD_DATA_FILE/);
  assert.match(analytics, /function web_register_download/);
  assert.match(analytics, /2592000/);
  assert.match(analytics, /600/);
  assert.match(functions, /function tracked_download_url/);
  assert.match(download, /hash_equals/);
  assert.match(download, /realpath\(FILES_ROOT\)/);
  assert.match(download, /web_register_download/);
  assert.match(download, /\['GET', 'HEAD'\]/);
  assert.match(download, /\$requestMethod === 'GET'/);
  assert.match(download, /Location:.*public_file_url/s);
  assert.match(partials, /web_format_download_count/);
  assert.match(releases, /web_download_count/);
  assert.doesNotMatch(functions.match(/function release_payload[\s\S]+$/)?.[0] || "", /tracked_download_url/);
});
